
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import models.CoachModel;
import models.ProfileModel;
import models.RegisteredSportModel;

public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddSportSchedule = new javax.swing.JButton();
        btnAddCoach = new javax.swing.JButton();
        btnAddSport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDisplayCoaches = new javax.swing.JButton();
        btnDispaySports = new javax.swing.JButton();
        btnDisplaySportSchedules = new javax.swing.JButton();
        btnDisplayStudents = new javax.swing.JButton();
        btnDisplayRegisteredStudents = new javax.swing.JButton();
        btnDisplayFeedbacks = new javax.swing.JButton();
        btnDisplayCoachesSorted = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etSearchCoach = new javax.swing.JTextField();
        etSearchStudent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSearchStudent = new javax.swing.JButton();
        btnSearchCoach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add Records");

        btnAddSportSchedule.setText("Sport Schedule");
        btnAddSportSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSportScheduleActionPerformed(evt);
            }
        });

        btnAddCoach.setText("Coach");
        btnAddCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoachActionPerformed(evt);
            }
        });

        btnAddSport.setText("Sport");
        btnAddSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSportActionPerformed(evt);
            }
        });

        jLabel2.setText("Display Records");

        btnDisplayCoaches.setText("Coaches");
        btnDisplayCoaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCoachesActionPerformed(evt);
            }
        });

        btnDispaySports.setText("Sports");
        btnDispaySports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispaySportsActionPerformed(evt);
            }
        });

        btnDisplaySportSchedules.setText("Sport Schedules");
        btnDisplaySportSchedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySportSchedulesActionPerformed(evt);
            }
        });

        btnDisplayStudents.setText("Students");
        btnDisplayStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayStudentsActionPerformed(evt);
            }
        });

        btnDisplayRegisteredStudents.setText("Registered Students");
        btnDisplayRegisteredStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayRegisteredStudentsActionPerformed(evt);
            }
        });

        btnDisplayFeedbacks.setText("Feedbacks");
        btnDisplayFeedbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayFeedbacksActionPerformed(evt);
            }
        });

        btnDisplayCoachesSorted.setText("Coaches (sorted)");
        btnDisplayCoachesSorted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCoachesSortedActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin Dashboard");

        jLabel4.setText("Search");

        jLabel5.setText("Coach ID");

        jLabel6.setText("Student ID");

        btnSearchStudent.setText("Search");
        btnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentActionPerformed(evt);
            }
        });

        btnSearchCoach.setText("Search");
        btnSearchCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCoachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDisplayCoachesSorted, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDisplayStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDisplayCoaches, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAddSport, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btnAddSportSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnDispaySports, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDisplayRegisteredStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDisplaySportSchedules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDisplayFeedbacks, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(etSearchCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnSearchCoach)))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnSearchStudent)
                                .addGap(43, 43, 43)))
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSportSchedule)
                    .addComponent(btnAddCoach)
                    .addComponent(btnAddSport))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySportSchedules)
                    .addComponent(btnDisplayCoaches)
                    .addComponent(btnDispaySports))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplayStudents)
                    .addComponent(btnDisplayRegisteredStudents)
                    .addComponent(btnDisplayFeedbacks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplayCoachesSorted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnSearchStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etSearchCoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnSearchCoach)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSportActionPerformed
        // TODO add your handling code here:
        new AddSport().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddSportActionPerformed

    private void btnAddCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoachActionPerformed
        // TODO add your handling code here:
        new AddCoach().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddCoachActionPerformed

    private void btnAddSportScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSportScheduleActionPerformed
        // TODO add your handling code here:
        new AddSportSchedule().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddSportScheduleActionPerformed

    private void btnDisplayCoachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCoachesActionPerformed
        // TODO add your handling code here:
        new DisplayCoaches().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisplayCoachesActionPerformed

    private void btnDispaySportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispaySportsActionPerformed
        // TODO add your handling code here:
        new DisplaySports().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDispaySportsActionPerformed

    private void btnDisplaySportSchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySportSchedulesActionPerformed
        // TODO add your handling code here:
        new DisplaySportsSchedules().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisplaySportSchedulesActionPerformed

    private void btnDisplayStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayStudentsActionPerformed
        // TODO add your handling code here:
        new DisplayStudents().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisplayStudentsActionPerformed

    private void btnDisplayRegisteredStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayRegisteredStudentsActionPerformed
        // TODO add your handling code here:
        new DisplayRegisteredStudents().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisplayRegisteredStudentsActionPerformed

    private void btnDisplayFeedbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayFeedbacksActionPerformed
        // TODO add your handling code here:
        new DisplayFeedbacks().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisplayFeedbacksActionPerformed

    private void btnDisplayCoachesSortedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCoachesSortedActionPerformed
        // TODO add your handling code here:
        new DisplayCoachesSorted().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisplayCoachesSortedActionPerformed

    private void btnSearchCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCoachActionPerformed
        // TODO add your handling code here:
        String coachId = etSearchCoach.getText().trim();
        
        if(coachId.isEmpty()){
            showDialog("Coach ID is empty");
            return;
        }
        
        CoachModel c = getCoach(coachId);
        if(c == null){
            showDialog("Coach with id "+coachId+" not found");
        } else {
            StringBuilder sb = new StringBuilder();
            sb.append("Coach ID: ");
            sb.append(c.getCoachID());
            sb.append("\n");
            sb.append("Coach Name: ");
            sb.append(c.getCoachName());
            sb.append("\n");
            sb.append("Join Date: ");
            sb.append(c.getJoinDate());
            sb.append("\n");
            sb.append("Sports Center: ");
            sb.append(c.getSportsCenter());
            sb.append("\n");
            sb.append("Hourly Rate: ");
            sb.append(c.getHourlyRate());
            sb.append("\n");
            sb.append("Phone: ");
            sb.append(c.getPhone());
            sb.append("\n");
            sb.append("Address: ");
            sb.append(c.getAddress());
            sb.append("\n");
            sb.append("Sport ID: ");
            sb.append(c.getSportId());
            sb.append("\n");
            sb.append("Sport Name: ");
            sb.append(c.getSportName());
            
            showDialog(sb.toString());
        }
    }//GEN-LAST:event_btnSearchCoachActionPerformed

    private void btnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentActionPerformed
        // TODO add your handling code here:
         String studentId = etSearchStudent.getText().trim();
        
        if(studentId.isEmpty()){
            showDialog("Student ID is empty");
            return;
        }
        
        ProfileModel s = getStudent(studentId);
        
        if(s == null){
            showDialog("Student with id "+studentId + " not found");
           
        }else {
//            private String id;
//    private String firstName;
//    private String lastName;
//    private String dob;
//    private String gender;
//    private String address;
//    private String state;
//    private String passcode;
//    private String email;
//    private String contact;
//    private String emergencyContact;
            StringBuilder sb = new StringBuilder();
            sb.append("Student ID: ");
            sb.append(s.getId());
            sb.append("\n");
            sb.append("Full Name: ");
            sb.append(s.getFirstName()).append(s.getLastName());
            sb.append("\n");
            sb.append("Date of birth: ");
            sb.append(s.getDob());
            sb.append("\n");
            sb.append("Gender: ");
            sb.append(s.getGender());
            sb.append("\n");
            sb.append("Address: ");
            sb.append(s.getAddress());
            sb.append("\n");
            sb.append("State: ");
            sb.append(s.getState());
            sb.append("\n");
            sb.append("Passcode: ");
            sb.append(s.getPasscode());
            sb.append("\n");
            sb.append("Email: ");
            sb.append(s.getEmail());
            sb.append("\n");
            sb.append("Contack Number: ");
            sb.append(s.getContact());
            sb.append("\n");
            sb.append("Emergency Contact Number: ");
            sb.append(s.getEmergencyContact());
            
            showDialog(sb.toString());
        }
    }//GEN-LAST:event_btnSearchStudentActionPerformed

    private ProfileModel getStudent(String id){
        String line = "";
        try {
           BufferedReader br= new BufferedReader(new FileReader("profiles.txt"));
           while((line = br.readLine()) != null){
               if(line.contains("|")){
                       String[] info = line.split("\\|");
                       if(info[0].equals(id)){
                           ProfileModel c= new ProfileModel(
                       info[0],
                       info[1],
                       info[2],
                       info[3],
                       info[4],
                       info[5],
                       info[6],
                       info[7],
                       info[8],
                       info[9],
                       info[10]
                           );
                           
                           return c;
                       }
                       
               }
           }
           br.close();
           return null;
        } catch (FileNotFoundException ex) {
           System.err.println("Error reading profiles.txt");
           return null;
        } catch (IOException ex) {
            System.err.println("Error reading profiles.txt");
            return null;
        }
    }
    
    private CoachModel getCoach(String id){
        String line = "";
        try {
           BufferedReader br= new BufferedReader(new FileReader("coaches.txt"));
           while((line = br.readLine()) != null){
               if(line.contains("|")){
                       String[] info = line.split("\\|");
                       if(info[0].equals(id)){
                           CoachModel c= new CoachModel(
                       info[0],
                       info[1],
                       info[2],
                       info[3],
                       Integer.parseInt(info[4]),
                       info[5],
                       info[6],
                       info[7],
                       info[8]);
                           
                           return c;
                       }
                       
               }
           }
           br.close();
           return null;
        } catch (FileNotFoundException ex) {
           System.err.println("Error reading coaches.txt");
           return null;
        } catch (IOException ex) {
            System.err.println("Error reading coaches.txt");
            return null;
        }
    }
    
    private void showDialog(String msg){
        JOptionPane.showMessageDialog(this, msg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCoach;
    private javax.swing.JButton btnAddSport;
    private javax.swing.JButton btnAddSportSchedule;
    private javax.swing.JButton btnDispaySports;
    private javax.swing.JButton btnDisplayCoaches;
    private javax.swing.JButton btnDisplayCoachesSorted;
    private javax.swing.JButton btnDisplayFeedbacks;
    private javax.swing.JButton btnDisplayRegisteredStudents;
    private javax.swing.JButton btnDisplaySportSchedules;
    private javax.swing.JButton btnDisplayStudents;
    private javax.swing.JButton btnSearchCoach;
    private javax.swing.JButton btnSearchStudent;
    private javax.swing.JTextField etSearchCoach;
    private javax.swing.JTextField etSearchStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
