
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.SportScheduleModel;


public class RegisterSport extends javax.swing.JFrame {

    ArrayList<SportScheduleModel> schedulesList = new ArrayList<>();
    String[] columnNames = {"ID", "Sport ID", "Sport", "Coach ID", "Coach Name", "Sports Center", "Start Time", "End Time", "Total hours"};
    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0){
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    private final String id;
    
    public RegisterSport(String id) {
        this.id = id;
        loadCoaches();
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sport Schedules");

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEdit.setText("Register");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow < 0){
            showDialog("Select a schedule to register");
        } else {
            SportScheduleModel scheduleModel = schedulesList.get(selectedRow);
            registerSport(scheduleModel);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new StudentDashboard(id).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void showDialog(String msg){
        JOptionPane.showMessageDialog(this, msg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayCoaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayCoaches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadCoaches() {
        schedulesList.clear();
        String line = "";
        try {
           BufferedReader br= new BufferedReader(new FileReader("schedules.txt"));
           while((line = br.readLine()) != null){
               if(line.contains("|")){
                       String[] info = line.split("\\|");
                       Object[] obj = {
                       info[0],
                       info[1],
                       info[2],
                       info[3],
                       info[4],
                       info[5],
                       info[6],
                       info[7],
                       info[8]
                       };
                       
                       SportScheduleModel schedule= new SportScheduleModel(
                       info[0],
                       info[1],
                       info[2],
                       info[3],
                       info[4],
                       info[5],
                       info[6],
                       info[7],
                       Integer.parseInt(info[8]));
                       
                   schedulesList.add(schedule);
                   tableModel.addRow(obj);
               }
           }
           br.close();
        } catch (FileNotFoundException ex) {
            System.err.println("Error reading schedules.txt");
        } catch (IOException ex) {
            System.err.println("Error reading schedules.txt");
        }
    }

    private void registerSport(SportScheduleModel sport) {
        
        if(alreadyRegistered(id)){
            showDialog("Sport is already registered");
            return;
        }
        
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("registered.txt", true));
            PrintWriter pw = new PrintWriter(bw);
            pw.println(id + "|"+
                    sport.getId() + "|"+
                    sport.getSportID()+"|"+sport.getSportName()+"|"+
                    sport.getCoachID()+"|"+sport.getCoachName()+"|"+
                    sport.getSportsCenter()+"|"+sport.getStartTime()+"|"+sport.getEndTime()+"|"+
                    sport.getHours());
            bw.close();
            pw.close();
            showDialog("Sport Registered Successfully");
            new StudentDashboard(id).setVisible(true);
            dispose();
        } catch (IOException ex) {
            System.err.println("Error reading registered.txt");
        }
    }
    
    private boolean alreadyRegistered(String id){
        String line = "";
        try {
           BufferedReader br= new BufferedReader(new FileReader("registered.txt"));
           while((line = br.readLine()) != null){
               if(line.contains("|")){
                       String[] data = line.split("\\|");
                       if(data[0].equals(id)){
                           return true;
                       }
               }
           }
           br.close();
           return false;
        } catch (FileNotFoundException ex) {
           System.err.println("Error reading registered.txt");
           return false;
        } catch (IOException ex) {
            System.err.println("Error reading registered.txt");
            return false;
        }
    }
}
